import n from"./supercomponent.js";import{renderMarkdown as o}from"./markdown.js";import{message as r,register as a}from"./messaging.js";import{copyToClipboard as l}from"./clipboard.js";import{navigate as c}from"./navigation.js";class h extends n{constructor(){super();this.handleClick=e=>{const t=e.target;if(t instanceof HTMLAnchorElement&&t.target!=="_blank"&&t.getAttribute("href")&&!t.dataset.noHijack){e.preventDefault(),e.stopPropagation();const i=t.getAttribute("href").replace(location.origin,"").replace(/^\//,"").trim();c(i)}};this.copyCodeToClipboard=e=>{const t=e.currentTarget,s=t.parentElement.querySelector("code").innerText.trim();l(s),t.focus(),t.classList.add("is-success"),setTimeout(()=>{t.classList.remove("is-success")},3e3)};this.copyLinkToClipboard=e=>{e.preventDefault();const t=e.currentTarget;location.hash=t.dataset.hash};this.state="LOADING",this.stateMachine={LOADING:{PASS:"IDLING",FAIL:"ERROR"},ERROR:{LOAD:"LOADING"},IDLING:{LOAD:"LOADING"}},this.model={html:""},a("renderer",this.inbox.bind(this)),this.render()}inbox(e){const{slug:t}=e.data;this.fetchDoc(t)}async fetchDoc(e){this.state!=="LOADING"&&(this.trigger("LOAD"),r({recipient:"subnav",data:{type:"load"}}));const t=await fetch(`/doc/${e.replace(/\.md/,"").trim()}`,{redirect:"follow"});if(t.ok){const i=await t.text(),s=await o(i);this.set({html:s}),this.trigger("PASS")}else this.set({html:'<p class="font-danger-700 absolute center">This component is missing documentation.</p>'}),this.trigger("FAIL")}connected(){this.addEventListener("click",this.handleClick,{capture:!0})}highlightSynatx(){this.querySelectorAll("pre code").forEach(e=>{e.innerHTML=e.innerHTML.replace(/\t/g,"    "),hljs?.highlightElement(e)})}scrubLinks(){const e=location.pathname.replace(/^\//,"").split("/");if(e.length){const t=new RegExp(/https?:\/\/|^\#/);this.querySelectorAll("a").forEach(i=>{const s=i.href.replace(location.origin,"").replace(location.pathname,"").trim();t.test(s)?i.dataset.noHijack="true":i.href=`/${e[0]}/${s.replace(/^\//,"").trim()}`}),this.querySelectorAll("img").forEach(i=>{const s=i.src.replace(location.origin,"");t.test(s)||(i.src=`/${e[0]}/${s.replace(/^\//,"").trim()}`)})}}pageJump(){if(location.hash.length){const e=this.querySelector(location.hash);e&&e.scrollIntoView()}else this.scrollTo({top:0,left:0,behavior:"auto"})}injectCopyToClipboardButtons(){this.querySelectorAll("pre code").forEach(e=>{const t=document.createElement("button");t.setAttribute("aria-label","copy source code to clipboard"),t.className="copy-to-clipboard",t.addEventListener("click",this.copyCodeToClipboard),t.innerHTML=`
                <svg xmlns="http://www.w3.org/2000/svg" class="copy" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                </svg>
                <svg xmlns="http://www.w3.org/2000/svg" class="success" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                </svg>
            `,e.parentElement.appendChild(t)})}injectPageJumpLinks(){const e=[];this.querySelectorAll("h1, h2, h3, h4, h5, h6").forEach(t=>{const i={label:t.innerText,hash:t.id,offset:parseInt(t.tagName.substr(1,1))-1};e.push(i);const s=document.createElement("a");s.className="page-jump-link-bttn",s.href=t.id,s.innerHTML=`
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
                </svg>
            `,s.setAttribute("aria-label","click to copy a direct link to this heading"),s.addEventListener("click",this.copyLinkToClipboard),s.dataset.hash=t.id,t.appendChild(s)}),r({recipient:"subnav",data:{type:"render",links:e}})}injectTableCellNames(){this.querySelectorAll("table tbody tr td").forEach(e=>{e.setAttribute("title",e.innerText.trim())})}render(){this.state==="LOADING"?this.innerHTML=`
                <txt-skel class="skeleton -heading w-1/4 mb-1"></txt-skel>
                <txt-skel class="skeleton -copy w-full mb-0.5"></txt-skel>
                <txt-skel class="skeleton -copy w-full mb-0.5"></txt-skel>
                <txt-skel class="skeleton -copy w-3/4 mb-0.5"></txt-skel>
            `:(this.innerHTML="",this.innerHTML+=this.model.html,this.highlightSynatx(),this.scrubLinks(),this.pageJump(),this.injectCopyToClipboardButtons(),this.injectPageJumpLinks(),this.injectTableCellNames())}}export{h as default};
